Add tests on the CI

diff --git a/.github/workflows/cpp-ci-serial-programs.yml b/.github/workflows/cpp-ci-serial-programs.yml
--- a/.github/workflows/cpp-ci-serial-programs.yml
+++ b/.github/workflows/cpp-ci-serial-programs.yml
@@ -35,7 +35,12 @@ jobs:
     steps:
     - uses: actions/checkout@v6
       with:
+        path: 'Arduino-Source'
         submodules: 'recursive'
+    - uses: actions/checkout@v6
+      with:
+        repository: 'PokemonAutomation/CommandLineTests'
+        path: 'CommandLineTests'
     - uses: jurplel/install-qt-action@v4
       with:
         version: ${{ matrix.qt_version }}
@@ -52,7 +57,7 @@ jobs:
         brew install opencv onnxruntime
     - name: Generate binaries
       run: |
-        cd SerialPrograms
+        cd Arduino-Source/SerialPrograms
         mkdir bin
         cd bin
         cmake .. -DQT_MAJOR:STRING=${{ matrix.qt_version_major }} ${{ matrix.cmake_additional_param }}
@@ -60,10 +65,20 @@ jobs:
     - name: Prepare upload folder
       if: startsWith(matrix.os, 'windows')
       run: |
-        del SerialPrograms/bin/RelWithDebInfo/SerialProgramsLib.lib
-        echo https://github.com/${{github.repository}}/commit/${{github.sha}} > SerialPrograms/bin/RelWithDebInfo/version.txt
+        echo https://github.com/${{github.repository}}/commit/${{github.sha}} > Arduino-Source/SerialPrograms/bin/RelWithDebInfo/version.txt
     - uses: actions/upload-artifact@v6
       if: startsWith(matrix.os, 'windows')
       with:
         name: Serial Programs (os=${{ matrix.os }} - compiler=${{ matrix.compiler }} - qt_version=${{ matrix.qt_version }})
-        path: SerialPrograms/bin/RelWithDebInfo
+        path: Arduino-Source/SerialPrograms/bin/RelWithDebInfo
+    - name: Run tests
+      if: startsWith(matrix.os, 'windows')
+      run: |
+        cd Arduino-Source/SerialPrograms/bin
+        $process = Start-Process -FilePath "./RelWithDebInfo/SerialPrograms.exe" `
+                                 -ArgumentList "--command-line-test-mode --command-line-test-folder ../../../CommandLineTests" `
+                                 -NoNewWindow -Wait -PassThru
+        if ($process.ExitCode -ne 0) {
+            Write-Error "Tests failed with exit code $($process.ExitCode)"
+            exit 1
+        }
